[package]
name = "semsimian_server"
version = "0.1.0"
edition = "2021"
# path = "src"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# semsimian = "*"
semsimian = { path = "../semsimian" }
rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = "*"
chrono = "0.4.31"
