[package]
name = "semsimian_server"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "semsimian_server"
path = "src/lib.rs"

[[bin]]
name = "semserver"
path = "src/bin.rs"

[dependencies]
semsimian = { git = "https://github.com/monarch-initiative/semsimian.git", commit= "b63a395" }
rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = "*"
chrono = ">=0.4.31"
lazy_static = { version = ">=1.4.0", features = [] }
