## defaults for _all_ profiles
[default]
address = "127.0.0.1"
port = 7878
# limits = { form = "64 kB", json = "1 MiB" }

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 9000
# limits = { json = "10MiB" }


## set only when compiled in release mode, i.e, `cargo build --release`
[release]
address = "0.0.0.0"
port = 9999
ip_header = false
