name: Test SemSimian Server
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version: [ '3.9', '3.12' ]
        os: [ ubuntu-latest ]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          target: 'x86_64'
          manylinux: auto
          args: --release --out dist -i ${{ matrix.python-version }}

      - name: Download Phenio
        run: |
          mkdir -p ~/.data/oaklib
          wget https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz -O ~/.data/oaklib/phenio.db.gz
          gunzip ~/.data/oaklib/phenio.db.gz

      - name: Run Tests
        run: |
          cargo build --verbose
          cargo test test_compare -- --nocapture
          cargo test test_search -- --nocapture
