name: Test SemSimian Server
on:
  push:
    branches: [ main, pin_to_py38 ]
  pull_request:
    branches: [ main, pin_to_py38 ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Python 3 Development Headers
        run: sudo apt-get update && sudo apt-get install python3-dev

      - name: Download Phenio
        run: |
          mkdir -p ~/.data/oaklib
          wget https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz -O ~/.data/oaklib/phenio.db.gz
          gunzip ~/.data/oaklib/phenio.db.gz

      - name: Install build-essential
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Install Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Run Tests
        run: |
          cargo build --verbose
          cargo test test_compare -- --nocapture
          cargo test test_search -- --nocapture
