name: Test SemSimian Server
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Phenio
        run: |
          wget https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz -O ~/.data/oaklib/phenio.db.gz
          gunzip ~/.data/oaklib/phenio.db.gz
      
      - run: |
          cargo build
          cargo test test_compare -- --nocapture
