name: Test SemSimian Server
on:
  push:
    branches: [ main pin_to_py38 ]
  pull_request:
    branches: [ main pin_to_py38 ]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Phenio
        run: |
          mkdir -p ~/.data/oaklib
          wget https://data.monarchinitiative.org/monarch-kg/latest/phenio.db.gz -O ~/.data/oaklib/phenio.db.gz
          gunzip ~/.data/oaklib/phenio.db.gz

      - name: Run Tests
        run: |
          cargo build
          cargo test test_compare -- --nocapture
          cargo test test_search -- --nocapture
